global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
  - job_name: 'node-exporter'

    static_configs:
    - targets: ['localhost:9090']
    - targets: ['localhost:9100']
